[Icon Theme]
Name=BeautyLineMustafa
Inherits=breeze

# Directory list
Directories=actions,animations,applets,apps,categories,devices,emblems,emotions,mimetypes,panel,places,preferences,status
Example=folder
DisplayDepth=32

FollowsColorScheme=true

DesktopDefault=48
ToolbarDefault=22
MainToolbarDefault=22
SmallDefault=16
PanelDefault=48
DialogDefault=32

KDE-Extensions=.svg

[animations]
Context=Animations
Size=22
MinSize=8
MaxSize=192

[actions]
Context=Actions
Size=22
MinSize=8
MaxSize=192

[categories]
Context=Categories
Size=22
MinSize=8
MaxSize=192

[devices]
Context=Devices
Size=22
MinSize=8
MaxSize=192

[emotions]
Context=Emotes
Size=22
MinSize=8
MaxSize=192

[actions]
Context=Status
Size=22
MinSize=8
MaxSize=192

[apps]
Context=Applications
Size=22
MinSize=8
MaxSize=192

[mimetypes]
Context=MimeTypes
Size=22
MinSize=8
MaxSize=192

[emblems]
Context=Emblems
Size=22
MinSize=8
MaxSize=192

[places]
Context=Places
Size=22
MinSize=8
MaxSize=192

[panel]
Context=Applications
Size=22
MinSize=8
MaxSize=192

[preferences]
Context=Applications
Size=22
MinSize=8
MaxSize=192

[status]
Context=Status
Size=22
MinSize=8
MaxSize=192
