#! /bin/sh

nitrogen --restore &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            5
bspc config window_gap              10

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config normal_border_color     "#484848"
bspc config focused_border_color    "#991F89"
bspc config urgent_border_color     "#B58900"
bspc config presel_border_color     "#26E2FF"

bspc config normal_frame_opacity    0.75
bspc config focused_frame_opacity   0.75

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

konsole
